os:
- linux
env:
  matrix:
  - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/
  global:
    secure: MjdqCPMV5iaByoY3m545Iw/S7UHbX5d3ZgU9H3c62Vo2WqJ12EWk4H0Z0HU+Ptu1+FriplfbnKKcfiE9zHam2yBs2XfhysWm/nOCk5eTetSpapYddWkwQaoEgxcan4kUyJiG0v4ZylorZea7d2wa9iKZKFQPChnvCI+Xd/9dlJs=
install:
- curl https://static.rust-lang.org/rustup.sh | sudo sh
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc
after_success: 'curl https://raw.githubusercontent.com/iron-bot/build-doc/master/build-doc.sh
  | sh '
