[package]

name = "router"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
license = "MIT"
version = "0.0.3"
description = "A router for the Iron framework."
repository = "https://github.com/iron/router"
documentation = "http://ironframework.io/doc/router/index.html"

[dependencies]
iron = "*"
route-recognizer = "*"

