[package]

name = "router"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.1.0"

[[lib]]

name = "router"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.route-recognizer]

git = "https://github.com/conduit-rust/route-recognizer.rs.git"

