[package]

name = "router"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.1.0"
readme = "README.md"
tags = ["web", "server", "middleware", "iron", "core", "router"]

[[lib]]

name = "router"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

[dependencies.rust-http]

git = "https://github.com/chris-morgan/rust-http.git"

